### ISSUE TITLE
Improve authority validation

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-java#180]
When creating a new application object, passing in "https://authority.com//tenant" fails with "java.lang.ArrayIndexOutOfBoundsException". 

We should either: 
- update authority validation logic should check that the value immediately after the first forward slash (the first value in the path) is valid, and if not throw a meaningful error
- Update authority creation logic to combine multiple forward slashes into a single forward slash

**Comment by vikasbo** [comment]
# Steps to reproduce

> What steps can reproduce the defect?

```
IPartnerCredentials appCredentials = 
      PartnerCredentials.getInstance()
      .generateByApplicationCredentials(clientId, applicationSecret, aadApplicationDomain)
```
throws:

```
2020-02-12 16:33:00,191 155022 ERROR [com.microsoft.aad.msal4j.ConfidentialClientApplication] (ForkJoinPool.commonPool-worker-1:) [Correlation ID: d1562f78-c8b2-4f14-9937-350080770ada] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
    java.lang.ArrayIndexOutOfBoundsException: 0
    	at com.microsoft.aad.msal4j.Authority.getTenant(Authority.java:88)
    	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:110)
    	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:131)
    	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:42)
    	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
    	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:49)
    	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
    	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
    	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
    	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
    	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

> Please share the setup, sample project, version of Java etc.

## Expected behavior

The above error does not make sense. Same code, same credentials worked in the previous version 1.5.1 but suddenly not working on switching to 1.5.3 latest build.

What could be the change that caused this and what is the root cause that can be attributed to the ArrayIndexOutOfBoundsException.

> Share the expected output

## Actual behavior

> What is the behavior observed?

## Diagnostic logs

> Please share test platform diagnostics logs.  
> The logs may contain test assembly paths, kindly review and mask those before sharing.

## Environment

> Please share additional details about your environment.
> Version

**Comment by vikasbo** [comment]
See https://github.com/microsoft/Partner-Center-Java/issues/113

[MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-java) must throw an understandable error message instead of throwing the run time error i.e. `ArrayIndexOutOfBoundsException`. Run time errors are a good sign that some validation is missing
