### ISSUE TITLE
PublicClientApplication.getAccounts() throw ClassCastException

### ISSUE THREAD

**Issue by jianghaolu** [AzureAD/microsoft-authentication-library-for-java#196]
Environment:
- Zulu 1.8
- MacOS 10.15
- KeyChain doesn't have a token cache available

Code:
```java
PersistenceTokenCacheAccessAspect accessAspect = new PersistenceTokenCacheAccessAspect(persistenceSettings);
PublicClientApplication.Builder applicationBuilder =  PublicClientApplication.builder(this.clientId);

pubClient = applicationBuilder
    .authority(authorityUrl)
    .setTokenCacheAccessAspect(accessAspect)
    .build();

Set<IAccount> accounts = pubClient.getAccounts().get();
```

Stack trace:
```
com.microsoft.aad.msal4j.MsalClientException: java.lang.ClassCastException: sun.net.www.protocol.https.HttpsURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:36)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:117)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:131)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:42)
	at com.microsoft.aad.msal4j.AccountsSupplier.get(AccountsSupplier.java:26)
	at com.microsoft.aad.msal4j.AccountsSupplier.get(AccountsSupplier.java:11)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1590)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassCastException: sun.net.www.protocol.https.HttpsURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection
	at com.microsoft.aad.msal4j.DefaultHttpClient.openConnection(DefaultHttpClient.java:72)
	at com.microsoft.aad.msal4j.DefaultHttpClient.executeHttpGet(DefaultHttpClient.java:37)
	at com.microsoft.aad.msal4j.DefaultHttpClient.send(DefaultHttpClient.java:28)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:33)
	... 12 more
```

**Comment by SomkaPe** [comment]
@jianghaolu  looks like an issue related to usage of custom class loader, It is not MSAL SDK issue.
Do you run test with PowerMock ? if yes try add @PowerMockIgnore({"javax.net.ssl.*"})

**Comment by jianghaolu** [comment]
Yes - we are using PowerMock. Thanks!
