### ISSUE TITLE
Instance discovery fails in Azure Databricks 6.4

### ISSUE THREAD

**Issue by lyytinen** [AzureAD/microsoft-authentication-library-for-java#213]
Instance discovery fails in Azure Databricks 6.4 when using msal4j 1.4.0:

```
Caused by: java.util.concurrent.CompletionException: com.microsoft.aad.msal4j.MsalClientException: com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class com.microsoft.aad.msal4j.InstanceDiscoveryMetadataEntry]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
 at [Source: {"tenant_discovery_endpoint":"https://login.microsoftonline.com/<tenant-id-removed>/v2.0/.well-known/openid-configuration","api-version":"1.1","metadata":[{"preferred_network":"login.microsoftonline.com","preferred_cache":"login.windows.net","aliases":["login.microsoftonline.com","login.windows.net","login.microsoft.com","sts.windows.net"]},{"preferred_network":"login.partner.microsoftonline.cn","preferred_cache":"login.partner.microsoftonline.cn","aliases":["login.partner.microsoftonline.cn","login.chinacloudapi.cn"]},{"preferred_network":"login.microsoftonline.de","preferred_cache":"login.microsoftonline.de","aliases":["login.microsoftonline.de"]},{"preferred_network":"login.microsoftonline.us","preferred_cache":"login.microsoftonline.us","aliases":["login.microsoftonline.us","login.usgovcloudapi.net"]},{"preferred_network":"login-us.microsoftonline.com","preferred_cache":"login-us.microsoftonline.com","aliases":["login-us.microsoftonline.com"]}]}; line: 1, column: 174] (through reference chain: com.microsoft.aad.msal4j.AadInstanceDiscoveryResponse["metadata"]->Object[][0])
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:93)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`
```
Executing the same code against the same tenant locally works fine.

**Comment by lyytinen** [comment]
Downgrading to msal4j v1.2.0 (which still used Gson for serialization) can be used as a workaround.

**Comment by lyytinen** [comment]
Azure Databricks 6.4 based on Spark 2.4.5 which in turn appears to load an older jackson version that in my understanding does not support `@ConstructorProperties`.

**Comment by sangonzal** [comment]
@lyytinen Do you know what version of Jackson is being loaded by Databricks?

**Comment by lyytinen** [comment]
Their parent pom says it's jackson 2.6.7:

https://github.com/apache/spark/blob/v2.4.5/pom.xml#L161

Support for `@ConstructorProperties` was added in jackson 2.7.0 I think.

I know this is not an issue in the library as such but Spark 2.4.5 is the latest release so this affects all spark clusters out there (including Azure Databricks and Azure HDInsight).

Not sure if adding an additional no-args constructor to your domain objects would help and what would you think about it?

**Comment by lyytinen** [comment]
Alternative solution to downgrade: version 1.4.0 works in Spark if you shade the jackson dependency.
