### ISSUE TITLE
Dependencies broken

### ISSUE THREAD

**Issue by MBurchard** [AzureAD/microsoft-authentication-library-for-java#214]
See this comment I made for com.nimbusds:oauth2-oidc-sdk:7.3: https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/294/dependency-resolution-broken

Looking at the versions at https://mvnrepository.com/artifact/com.microsoft.azure/msal4j/1.4.0 it should be possible to use oauth2-oidc-sdk:7.3.

But then there is a runtime error because MSAL uses some JSON functionality from net.minidev:json-smart:2.3.

    JSONObject.getAsString(String key)

With oauth2-oidc-sdk:7.3 they have downgraded json-smart to version 1.3.1.

This is not good behaviour, of course, but it would be even better if MSAL included a direct dependency when it requires a specific library and version.

I solved it in my project by adding a direct dependency that I of course normally not need.

	implementation 'javax.inject:javax.inject:1',
			'com.google.code.findbugs:jsr305:3.0.2',
			'org.springframework.boot:spring-boot-starter-web',
			'org.springframework.boot:spring-boot-starter-security',
			'net.minidev:json-smart:2.3',
			'com.nimbusds:oauth2-oidc-sdk:7.3',
			"com.microsoft.azure:msal4j:1.4.0",
			"org.apache.commons:commons-text:1.8",
			'com.microsoft.graph:microsoft-graph:1.7.1'

**Comment by lyytinen** [comment]
Are we talking about this?

```
Caused by: java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:105)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createOauthHttpRequest(TokenRequestExecutor.java:46)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:34)
	at com.microsoft.aad.msal4j.ClientApplicationBase.acquireTokenCommon(ClientApplicationBase.java:91)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:52)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:57)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I rebuilt my code and now it just fails with this exception.

**Comment by MBurchard** [comment]
It might be... I have debugged into it, and the reason is because of missing getAsString Method...

**Comment by sangonzal** [comment]
@MBurchard You are right, this should be listed as a direct dependency in MSAL. I will mark as a bug, and we will talk to the team to fix this and release this week. 

Ideally we should totally get rid of this dependency, as it's only used in one place.

**Comment by SomkaPe** [comment]
we are currently using oauth2-oidc-sdk:6.5 version, not 7.3.
So of cause there is not guarantee that it is going to work with 7.3.

"MSAL included a direct dependency when it requires a specific library and version" - not sure about it.

**Comment by sangonzal** [comment]
@SomkaPe The bug is using JSONObject without including it in the pom.xml: 
https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/0644297c911892e95e0432100f218aa82a28ff21/src/main/java/com/microsoft/aad/msal4j/TokenResponse.java#L15

We should either add this to pom.xml or get rid of this dependency

**Comment by SomkaPe** [comment]
Dependencies that you explicitly rely on should be declared. Regarding net.minidev.json.JSONObject class, it is used in some public oauth2-oidc-sdk APIs - for example in com.nimbusds.oauth2.sdk.http.HTTPResponse, So it is part of oauth2-oidc-sdk API. Outside of oauth2-oidc-sdk API we do not use oauth2-oidc-sdk API

**Comment by MBurchard** [comment]
As @sangonzal mentioned and showed you MSAL directly uses net.minidev.json.JSONObject...

   import net.minidev.json.JSONObject;

**Comment by SomkaPe** [comment]
yes, as I already explained because it is part of           
  <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
dependency, we do not use it otherwise

**Comment by lyytinen** [comment]
@SomkaPe You are using it in the TokenResponse class as shown above by @sangonzal. You are explicitly importing the JSONObject class and then using it in the parseJsonObject method. Due to the downgrade reported by @MBurchard this part of the code now throws an exception at runtime.

**Comment by MBurchard** [comment]
It's a funny discussion. Would suggest that you @SomkaPe take a look into the MSAL Code that @sangonzal mentioned: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/214#issuecomment-617433319

**Comment by navyasric** [comment]
We plan to upgrade Nimbus SDK version as an enhancement in future releases. This can be tracked here: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/223

**Comment by SomkaPe** [comment]
@lyytinen @MBurchard  please read my answers again

**Comment by schuch** [comment]
This is IMHO still an open issue.

As @lyytinen and @MBurchard stated correctly, the code of this MSAL Java Library has a compile time dependency ([TokenResponse.java#L71](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/v1.6.0/src/main/java/com/microsoft/aad/msal4j/TokenResponse.java#L71)) on the [`json-smart:2.3`](https://netplex.github.io/json-smart/) library which is transitively imported via `oauth2-oidc-sdk`.

The `oauth2-oidc-sdk` POM (7.4 and above) allows different versions of `json-smart`: `[1.3.1,2.3]`. (refer to https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/233/remove-dependency-on-asm-json-smart)

By not declaring the `json-smart` compile time dependency, is causing a runtime error, if maven chooses to resolve `json-smart:1.3.1`, which is perfectly fine for `oauth2-oidc-sdk`, but not for the code in this MSAL Java Library.

The runtime error is:
```
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: net.minidev.json.JSONObject.getAsString(Ljava/lang/String;)Ljava/lang/String;

	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NoSuchMethodError: net.minidev.json.JSONObject.getAsString(Ljava/lang/String;)Ljava/lang/String;
	at com.microsoft.aad.msal4j.TokenResponse.parseJsonObject(TokenResponse.java:57)
	at com.microsoft.aad.msal4j.TokenResponse.parseHttpResponse(TokenResponse.java:34)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:61)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:38)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:117)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 5 more
```
This was also reported in #240

**Comment by SomkaPe** [comment]
@electrified  1.6.1 version released, please try

**Comment by electrified** [comment]
Thanks @SomkaPe , I will give it a go.

**Comment by seblea** [comment]
Caused by: java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:103)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createOauthHttpRequest(TokenRequestExecutor.java:57)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:35)

**Comment by seblea** [comment]
I have seen that this bug is closed . I am using spark 2.4  with scala version 2.11 and jackson.version 2.13 . I have this dependancy in my pom  <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>msal4j</artifactId>
            <version>1.11.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-scala_${scala.binary.version}</artifactId>
            <version>${jackson.version}</version>
        </dependency> . .But getting this error
