### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/sun/net/ssl/internal/www/protocol/https/HttpsURLConnectionOldImpl

### ISSUE THREAD

**Issue by Narcolapser** [AzureAD/microsoft-authentication-library-for-java#235]
I am attempting to patch Azure AD authentication into our old ColdFusion server. I'm using [this](https://github.com/Azure-Samples/ms-identity-java-webapp/tree/9df692575c7220f49f0178213afee9155cec6ed2/msal-java-webapp-sample) as an example of how to make a java class that manages the login process. My thought process is that since CF does not have this ability natively (there is an OAuth but it's MS support is shaky) I can just use the msal4j library to add it in. Done it before with other things.

However, around [this](https://github.com/Azure-Samples/ms-identity-java-webapp/blob/9df692575c7220f49f0178213afee9155cec6ed2/msal-java-webapp-sample/src/main/java/com/microsoft/azure/msalwebsample/AuthHelper.java#L117) step in the process I get this error:

```
05/11 14:20:52 [Thread-28] ERROR [Correlation ID: 9c6feace-4b68-46c7-884f-d50760dd4727] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizatio
nGrantSupplier failed.
com.microsoft.aad.msal4j.MsalClientException: java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be ca
st to javax.net.ssl.HttpsURLConnection
        at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:36)
        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:117)
        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:131)
        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:42)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
        at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:49)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: com.sun.net.ssl.internal.www.protocol.https.HttpsURLConnectionOldImpl cannot be cast to javax.net.ssl.HttpsURLConnection
        at com.microsoft.aad.msal4j.DefaultHttpClient.openConnection(DefaultHttpClient.java:72)
        at com.microsoft.aad.msal4j.DefaultHttpClient.executeHttpGet(DefaultHttpClient.java:37)
        at com.microsoft.aad.msal4j.DefaultHttpClient.send(DefaultHttpClient.java:28)
        at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:33)
        ... 9 more

```

I looked into it and the class in question is part of the rt.jar for my java version. So I figured I must have a version of java to old for this example, but then I saw the library supports java 8 or higher and behold:

```
[root@dev-coldfusion logs]# java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

```

I'm on java 8. This *should* work but it isn't. Any idea what's wrong here or how to work around it?

**Comment by SomkaPe** [comment]
msal4j uses built-in JDK SSL library. From posted log, looks like JVM configured with external library (through system property java.protocol.handler.pkgs = com.sun.net.ssl.internal.www.protocol)

If you want to use custom http client please have a look at https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Configure-Http-Client

**Comment by Narcolapser** [comment]
That makes sense. But if I am reading [this](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpRequest.html) correctly, facilities like HttpRequest are not available in java 8. Is that correct? Or have I missed the library that allows one to use these in java 8?

**Comment by SomkaPe** [comment]
HttpRequest used in IHttpClient interface is from com.microsoft.aad.msal4j  package.

https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/master/src/integrationtest/java/com.microsoft.aad.msal4j/OkHttpClientAdapter.java  - example of custom http client

**Comment by Narcolapser** [comment]
Aah, ok. I've imported that adapter into my code and that has gotten me past this issue. Now on to other issues. Thank you.
