### ISSUE TITLE
[BUG] Device Code Auth flow validation of ADFS authorities fails.

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#270]
**Bug Description**
Device Code Auth Flow fails when ADFS authorities are passed in when trying to validate them.

**Steps To Reproduce**
Here's the code sample to reproduce the issue.
``` java
        PublicClientApplication a =  PublicClientApplication.builder("PublicClientId")
                                             .authority("https://fs.msidlab8.com/adfs/")
                                             .build();
        HashSet<String> strings = new HashSet<>();
        strings.add("openid");
        DeviceCodeFlowParameters parameters = DeviceCodeFlowParameters.builder(strings, deviceCode -> System.out.println(deviceCode.message())).build();


        String token = a.acquireToken(parameters).get().accessToken();
```

**Expected Behavior**
Should print out Device Code and Browser URL to authenticate at.

**Actual Behavior:** 
Exception in thread "main" java.util.concurrent.ExecutionException: com.microsoft.aad.msal4j.MsalServiceException: AADSTS50049: Unknown or invalid instance.
Trace ID: 078b203c-6ac4-4150-b16a-5e365c32f600
Correlation ID: a5350b67-0853-4e94-a10f-d47b8b2bf951
Timestamp: 2020-08-26 20:44:25Z
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2070)
	at vinay.test.demo.DACCredentialsDemo.main(DACCredentialsDemo.java:146)
Caused by: com.microsoft.aad.msal4j.MsalServiceException: AADSTS50049: Unknown or invalid instance.
Trace ID: 078b203c-6ac4-4150-b16a-5e365c32f600
Correlation ID: a5350b67-0853-4e94-a10f-d47b8b2bf951
Timestamp: 2020-08-26 20:44:25Z
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.validate(AadInstanceDiscoveryProvider.java:142)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:134)
	at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:42)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.execute(AcquireTokenByDeviceCodeFlowSupplier.java:23)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1771)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by SomkaPe** [comment]
ADFS authority validation is not supported right now

**Comment by g2vinay** [comment]
> ADFS authority validation is not supported right now

Thanks for the quick response.
Yep, so similar to Msal for .NET, the validation for ADFS authorities should be disabled in the MSAL logic ?

**Comment by Avery-Dunn** [comment]
I believe ADFS2019 for device code flow was supported after [this change](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/237), and it should be working as of version 1.6

Using your example code and the latest version (1.6.2), I wasn't able to recreate the error you got, the code provided a URL and device code as expected:
![image](https://user-images.githubusercontent.com/62066438/91363387-62bcf600-e7b1-11ea-9c21-15ebe03dc6db.png)

We have some automated tests for the device code flow that uses the same authority you used, and those run fine as well.

**Comment by g2vinay** [comment]
I am using version 1.6.1
So, it was fixed for version 1.6.2 (released 9 days back).

Thank you for the information.
I will upgrade msal library from 1.6.1 to 16.2

**Comment by Avery-Dunn** [comment]
@g2vinay : Any luck getting this to work after upgrading to 1.6.2? Are you still having this issue, or any others?

**Comment by Avery-Dunn** [comment]
Closing due to inactivity. If you are still having this issue or any others, feel free to leave a comment or re-open this thread.
