### ISSUE TITLE
[BUG] MSAL Logic to retrieve accounts from the cache for ADFS authorities throws NullPointerException.

### ISSUE THREAD

**Issue by g2vinay** [AzureAD/microsoft-authentication-library-for-java#271]
**Bug Description**
MSAL Caching mechanism doesn't support ADFS authorities and fails with a NullPointerException.

The MSAL logic tries to find environment aliases for ADFS authorities and finds nothing, so the HashSet representing environment aliases is null. 
When the code tries to access this HashSet while filtering accounts from the cache, it throws a NPE.

For ADFS authorities, the environment aliases HashSet should contain the ADFS authority alias itself.

**Steps To Reproduce**
Here's the code sample to reproduce the issue.
``` java
        PublicClientApplication publicClientApplication =  PublicClientApplication.builder("PublicClientId")
                                             .authority("https://fs.msidlab8.com/adfs/")
                                             .validateAuthority(false)
                                             .build();

        HashSet<String> scopes = new HashSet<>();
        scopes.add("openid");

        InteractiveRequestParameters interactiveRequestParameters = InteractiveRequestParameters.builder(new URI("http://localhost:8080"))
                .scopes(scopes)
                .build();

// Use the username and password from the Identity Labs Test Account: https://docs.msidlab.com/accounts/adfsv2019.html
        IAuthenticationResult result = publicClientApplication.acquireToken(interactiveRequestParameters).get();

        SilentParameters silentParameters = SilentParameters.builder(scopes, result.account()).build();

        String tokenFromSilentAuthentication = publicClientApplication.acquireTokenSilently(silentParameters).get().accessToken();
```

**Expected Behavior**
Should successfully acquire token silently from the cache.

**Actual Behavior:** 
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2070)
	at vinay.test.demo.DACCredentialsDemo.main(DACCredentialsDemo.java:160)
Caused by: java.lang.NullPointerException
	at com.microsoft.aad.msal4j.TokenCache.lambda$getAccountCacheEntity$8(TokenCache.java:449)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:548)
	at com.microsoft.aad.msal4j.TokenCache.getAccountCacheEntity(TokenCache.java:450)
	at com.microsoft.aad.msal4j.TokenCache.getCachedAuthenticationResult(TokenCache.java:484)
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:32)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1771)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by Avery-Dunn** [comment]
Hello @g2vinay : Much like your [other issue](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/270), I'm able to recreate this exception in version 1.6.1, but not in version 1.6.2

Try updating to the latest version and see if it still happens. This issue seems familiar to me, though I can't remember which commit had the fix.

**Comment by Avery-Dunn** [comment]
Closing due to inactivity. If you are still having this issue or any others, feel free to leave a comment or re-open this thread.
