### ISSUE TITLE
AuthenticationResultSupplier.java:89 - java.util.Collections$SingletonList cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by kmmuthu** [AzureAD/microsoft-authentication-library-for-java#274]
Facing this error while using the confidential-client sample code. 
https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/samples/confidential-client/ClientCredentialGrant.java

**Additional details:**
Public clients is set to "No" in Azure Authentication settings for this application.

**Error Trace:**
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:89)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)

**Comment by Avery-Dunn** [comment]
Hello @kmmuthu : I've just tried running the sample myself, and couldn't reproduce the issue. Could you post the full stack trace? Also, in the sample, what value(s) are you using for the `SCOPE` parameter? This is mostly a guess, but that parameter is a collection that becomes a string so it may be relevant here.

**Comment by kmmuthu** [comment]
Hi @Avery-Dunn ,

Please find below the stack trace:
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:89)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:105)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createOauthHttpRequest(TokenRequestExecutor.java:51)
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:36)
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:117)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)


I too doubt the SCOPE parameter as that sounds to be the source of this exception:
private static Set<String> SCOPE = Collections.singleton("");

**Comment by Avery-Dunn** [comment]
Strange, when I leave it empty or add "read" like you did, I also get an error. However, my error is about the scopes not being valid when getting an auth result, which is different from your error about casting to a string when serializing the parameters. What version/branch of the code are you using, and what version of Java? I've tried with both the dev and master branches, and Java 1.8

Also, try the following value for scopes `SCOPE = Collections.singleton("https://graph.windows.net/.default");`
That's the scope value that works for me, so if we're getting different errors but they're both related to scopes maybe it will work for you as well.

**Comment by kmmuthu** [comment]
I tried this scope initially and got the same error. 
I'm using java1.8 too.. I haven't checked out the code - rather pointing to this library directly like below.
                <dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>msal4j</artifactId>
			<version>1.6.2</version>
		</dependency>

**Comment by Avery-Dunn** [comment]
Perhaps it's a dependency issue, could you paste your pom.xml? The error seems to be occurring with a nimbusds.oauth2.sdk method, so maybe you have a different version locally than the 7.4 version the library uses, or there's some other dependency conflicting with something.

Also, have you made any changes to the sample, other than configuring the client ID/tenant ID/secret/scopes?

**Comment by kmmuthu** [comment]
Seems that was the problem. I had a much older version 5.24. I upgraded to 7.4 and able to generate the token. 
I am working on migrating from ADAL to MSAL, and got stuck with this issue. Thanks much @Avery-Dunn!
