### ISSUE TITLE
Provide more information in error case

### ISSUE THREAD

**Issue by ezienecker** [AzureAD/microsoft-authentication-library-for-java#328]
I run a simple example in my application to acquire a token. I get the following error message:

```
Caused by: com.microsoft.aad.msal4j.MsalClientException: Cached JWT could not be parsed: Invalid JWT serialization: Missing dot delimiter(s)
 	at com.microsoft.aad.msal4j.AuthenticationResult.getTenantProfile(AuthenticationResult.java:54) ~[msal4j-1.8.1.jar!/:1.8.1]
 	at com.microsoft.aad.msal4j.AuthenticationResult.tenantProfile(AuthenticationResult.java:353) ~[msal4j-1.8.1.jar!/:1.8.1]
 	at com.microsoft.aad.msal4j.AuthenticationResult.hashCode(AuthenticationResult.java:283) ~[msal4j-1.8.1.jar!/:1.8.1]
```

The confusing part, my sample app (just to play around) and the productive ap share the exactly the same code. But in my productive I get the stacktrace. It's really frustrating that there is now meaningful log!

Code sample:

```
ConfidentialClientApplication app =
					ConfidentialClientApplication.builder(clientId, ClientCredentialFactory.createFromSecret(secret))
							.authority("https://login.microsoftonline.com/tenant")
							.build();

			ClientCredentialParameters clientCredentialParam =
					ClientCredentialParameters.builder(Collections.singleton(SCOPE)).build();

			IAuthenticationResult
					result = app.acquireToken(clientCredentialParam).join();
```

**Comment by Avery-Dunn** [comment]
Hello @ezienecker : We use `com.nimbusds.jwt.JWTParser` for parsing JWT's, and unfortunately it doesn't give much error information when the JWT can't be parsed ([their parser](https://www.javadoc.io/doc/com.nimbusds/nimbus-jose-jwt/2.21/src-html/com/nimbusds/jwt/JWTParser.html) basically only has error messages saying the JWT has no periods, the header can't be parsed, or it doesn't know the algorithm). I suppose we could add a bit more information suggesting what could be wrong based on their error messages (like replacing their "Missing dot delimiter(s)" with something like "This JWT is either blank or invalid"), but it'd still be pretty generic and we'd need to keep up with any changes to a third-party library's error handling.

As for the error itself, I haven't been able to recreate it. could you provide a bit more info about your situation, and is there any other debug information? Off the top of my head I have two ideas about what could be going wrong:
- Is your production app is in some production environment, and your working sample app is in some other environment? If so, then there could be some network/firewall/proxy settings stopping the library from retrieving the tokens, leading to it trying to parse something that's blank.
- Are you using the same secret/tenant/app in each environment? If not, then there could be some misconfigured secret or permissions causing auth issues when trying to get the tokens.

**Comment by ezienecker** [comment]
@Avery-Dunn I have seen it that you use this lib. I think a big win for this issue could be if you print out the token in catch case (https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/v1.8.1/src/main/java/com/microsoft/aad/msal4j/AuthenticationResult.java#L82). 
I think you can leave it as it is but there should be the possibility to look at the JWT via logging.

I'm a bit wondering about this statement from you: "This JWT is either blank or invalid". is this in general or really specific on this topic? If it's specially on this topic, then I would appreciate it very much if you would adjust the following line https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/v1.8.1/src/main/java/com/microsoft/aad/msal4j/AuthenticationResult.java#L75 to check for both null and empty.

> Is your production app is in some production environment, and your working sample app is in some other environment? If so, then there could be some network/firewall/proxy settings stopping the library from retrieving the tokens, leading to it trying to parse something that's blank.

Both I started from my local machine. Only different the working one I started from IntelliJ and the other one I started from docker. But I can't think of any reason why Docker shouldn't let the request go out after but this can be something I will check.

> Are you using the same secret/tenant/client ID/user in each environment? If not, then there could be some misconfigured secret or permissions causing auth issues when trying to get the tokens.

Yes, credentials, tenant are exactly the same (for testing purposes I copy and paste it from one editor window to the other)

**Comment by Avery-Dunn** [comment]
@ezienecker I'm able to recreate the error message and definitely found a bug in the library, however I'm not sure if it's related to what you're doing: in your production app (or in any code that has this issue), are you trying to access the `tenantProfile` field of the `AuthenticationResult` class, or doing something that could cause all the fields in the auth result to be initialized?

Basically, [here](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/4715fcd4f9abe44ba2b508df07187831352f4057/src/main/java/com/microsoft/aad/msal4j/AuthenticationResult.java#L75) in `AuthenticationResult` we check if the ID token in the result is null before trying to get claims from it, but when doing the confidential client flow the ID token is an empty string, not just null, which we mistakenly try to parse. However, the method where your issue is happening is only called when the getter for `tenantProfile` is explicitly called, since it's one of several fields in `AuthenticationResult` where we use Lombok's ['lazy' annotation](https://projectlombok.org/features/GetterLazy) so it doesn't get initialized when the auth result is first created.

I'll have the PR with the fix soon, but like I said you might be having a different issue. For now, if the code that's failing is trying to access the `tenantProfile` field of `AuthenticationResult`, try getting rid of that access attempt and see if the issue still happens (if you have no explicit call to it, maybe some other dependency is loading all fields implicitly?). If you're still getting that exception, then there might be something specific to Docker causing the issue (have you tried/are you able to run the production app outside of Docker?)

**Comment by Avery-Dunn** [comment]
Closing due to inactivity. If you're still experiencing this issue or any related issues, feel free to reopen this thread or leave a comment.
