### ISSUE TITLE
Using msal4j raise AccessControlException when java SecurityManager is activated

### ISSUE THREAD

**Issue by pKrav75** [AzureAD/microsoft-authentication-library-for-java#360]
Hello,
I don't know if it is the correct place to place this 'question'.
I m trying to integrate msal4j in an application running with the Java SecurityManager activated.
It appears that HTTPHeader throws security exception
```java
2021-03-09 14:13:18.738 GMT INFO  - output:Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "os.arch" "read")
2021-03-09 14:13:18.740 GMT INFO  - output:	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
2021-03-09 14:13:18.740 GMT INFO  - output:	at java.security.AccessController.checkPermission(AccessController.java:886)
2021-03-09 14:13:18.741 GMT INFO  - output:	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
2021-03-09 14:13:18.741 GMT INFO  - output:	at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
2021-03-09 14:13:18.742 GMT INFO  - output:	at java.lang.System.getProperty(System.java:717)
2021-03-09 14:13:18.742 GMT INFO  - output:	at com.microsoft.aad.msal4j.HttpHeaders.<clinit>(HttpHeaders.java:20)
```
Which is quite understandable since this is executed in a ForkJoinPool that has no default permission.

Is there a preferred / pre configured way to override the currently used executor so I can grant the needed permissions. 
Did someone already experienced such 'issue'.
Any hints would help.
Thx

**Comment by pKrav75** [comment]
Actually, this is probably a full Java issue, not related, directly with msal4j.
I'v found a solution here https://stackoverflow.com/questions/34303094/is-it-not-possible-to-supply-a-thread-facory-or-name-pattern-to-forkjoinpool
Closing the track
