### ISSUE TITLE
Misleading error: Device authentication expired when should fail

### ISSUE THREAD

**Issue by ohadbitt** [AzureAD/microsoft-authentication-library-for-java#363]
Using msal4j 1.9.1 :
```scala
 val deviceCodeFlowParams: DeviceCodeFlowParameters = DeviceCodeFlowParameters.builder(scopes, deviceCodeConsumer).build
    clientApplication.acquireToken(deviceCodeFlowParams).join()
    ```

scopes here was given bad input (some name instead of URL) and the exception thrown is : 

java.util.concurrent.CompletionException: com.microsoft.aad.msal4j.MsalClientException: Expired Device code

	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:89)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1604)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: com.microsoft.aad.msal4j.MsalClientException: Expired Device code
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.acquireTokenWithDeviceCode(AcquireTokenByDeviceCodeFlowSupplier.java:68)
	at com.microsoft.aad.msal4j.AcquireTokenByDeviceCodeFlowSupplier.execute(AcquireTokenByDeviceCodeFlowSupplier.java:27)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
	... 8 more
	
	
I guess this is because expiresIn has a zero value but its missleading

**Comment by Avery-Dunn** [comment]
Hello @ohadbitt : Just to confirm the issue here: when trying to get a token using the device code flow, if the token request fails (in this case, because of bad input for scopes) the error message incorrectly says that the device code expired rather than saying the actual error, right? The issue is just unhelpful error messages, but otherwise the library is working when you expect it to work, and failing when you expect it to fail?

I'm able to reproduce that misleading error case and we definitely need to improve the error messages for this flow. We should be able to add these improvements as part of a release in the next week or two.
