### ISSUE TITLE
seeing intermittent read timeout as com.microsoft.aad.msal4j.MsalClientException: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by pobisw** [AzureAD/microsoft-authentication-library-for-java#364]
I am using the latest version of the library, but I am seeing this intermittent read timeout exceptions and I am not able to figure out the reason.
I see the the default readtimeout is already 15secs so doesnt look like increasing the timeout would solve the issue

Is it occurring because of concurrency ? I am pasting the exception stack trace and my code too, 

> "message": [Correlation ID: 436b3897-0b90-4600-8aa0-57f13031c084] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed., "logger_name": com.microsoft.aad.msal4j.ConfidentialClientApplication,

I am using msal4j in java project to fetch an app-only AAD token The mechanism works perfectly in staging, but in production I am seeing some error though for very small number of cases. Rest of all the call are successful

"message": [Correlation ID: 436b3897-0b90-4600-8aa0-57f13031c084] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed., "logger_name": com.microsoft.aad.msal4j.ConfidentialClientApplication,

"stack_trace":

> com.microsoft.aad.msal4j.MsalClientException: java.net.SocketTimeoutException: Read timed out at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:68) at com.microsoft.aad.msal4j.OAuthHttpRequest.send(OAuthHttpRequest.java:33) at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:36) at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:120) at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59) at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17) at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) Caused by: java.net.SocketTimeoutException: Read timed out at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) at java.net.SocketInputStream.read(SocketInputStream.java:171) at java.net.SocketInputStream.read(SocketInputStream.java:141) at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) at sun.security.ssl.InputRecord.read(InputRecord.java:503) at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) at java.io.BufferedInputStream.read(BufferedInputStream.java:345) at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347) at com.microsoft.aad.msal4j.DefaultHttpClient.readResponseFromConnection(DefaultHttpClient.java:107) at com.microsoft.aad.msal4j.DefaultHttpClient.executeHttpPost(DefaultHttpClient.java:63) at com.microsoft.aad.msal4j.DefaultHttpClient.send(DefaultHttpClient.java:37) at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:86) at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:64) ... 12 common frames omitted , "exception_class": com.microsoft.aad.msal4j.MsalClientException, "exception_message": java.net.SocketTimeoutException: Read timed out,

here is my code 
```

public class AADTokenProvider {
    private String scope;  
    private ConfidentialClientApplication app;
    private static final Logger LOGGER = LoggerFactory.getLogger(AADTokenProvider.class);

    public AADTokenProvider(AuthConfiguration authConfiguration, P12CertificateParser parser) throws MalformedURLException {
        this.scope = authConfiguration.getScope();

        this.app = ConfidentialClientApplication.builder(
            authConfiguration.getClientId(),
            ClientCredentialFactory.createFromCertificate(parser.getPrivateKey().get(), parser.getCertificate().get()))
            .authority(authConfiguration.getAuthority())
            .build();
    }

    public String getAccessToken() throws Exception{

        // With client credentials flows the scope is ALWAYS of the shape "resource/.default", as the
        // application permissions need to be set statically (in the portal), and then granted by a tenant administrator

        ClientCredentialParameters parameters =
                        ClientCredentialParameters
                                .builder(Collections.singleton(scope))
                                .build();                

        // Try to acquire a token. If successful, you should see
        // the token information printed out to console
        try {
            LOGGER.info("Fetching an app only AAD Token");
            IAuthenticationResult result = app.acquireToken(parameters).join();
            return result.accessToken();
        }
        catch(Exception e) {
            LOGGER.error("Token Fetching Failed");
            throw new RetryException(String.format("Token Fetching Failed", e.getCause().getMessage()));
        }       
    } 
```

I have 10 worker threads and 
I have created a single confidential client which is getting used by each of the worker, I did so that all the workers can use the same inmemory cache. not sure if thats the reason. Also I am creating the condifential client in the constructor, should I create it per reuqest in the getAccessToken method ?

**Comment by SomkaPe** [comment]
looks like server side throttling, acquireToken API do not use cache. So recommended pattern is first try to get token from cache by calling acquireTokenSilently, and if it failed call acquireToken api.

**Comment by pobisw** [comment]
@SomkaPe I read that for app-only token the in-memory cache is used by default and we dont need to use acquireTokenSilently API
https://stackoverflow.com/questions/61150094/how-do-i-use-msal4j-to-acquire-a-token-for-a-daemon
https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Acquiring-Tokens
![image](https://user-images.githubusercontent.com/28534218/112704384-70119e80-8ec0-11eb-8816-b674207492a9.png)

https://docs.microsoft.com/en-in/azure/active-directory/develop/scenario-daemon-acquire-token?tabs=dotnet#acquiretokenforclient-api

![image](https://user-images.githubusercontent.com/28534218/112704677-72c0c380-8ec1-11eb-81bb-d496d0051771.png)


https://github.com/Azure-Samples/ms-identity-java-daemon/blob/master/msal-client-credential-certificate/src/main/java/ClientCredentialGrant.java


this above example also doesnt use the acquireTokenCache silently so I assumed that I dont need to call acquireTokenSilently
is that wrong ?

**Comment by SomkaPe** [comment]
@pobisw you have published c# sample, please click on Java tab

**Comment by pobisw** [comment]
adding cache solved the issue, closing the thread
