### ISSUE TITLE
How to configure a the Java webapp behind a Proxy in Apache

### ISSUE THREAD

**Issue by marcgise** [AzureAD/microsoft-authentication-library-for-java#365]
Dear,
I'm trying to configure the example webapp Java application (https://docs.microsoft.com/azure/active-directory/develop/quickstart-v2-java-webapp) to work behind a ProxyPass and ProxyPassReverse in Apache, but I can't get it work.

In Apache I have the following configuracion:
```
ProxyPass               /testazure              http://localhost:8080
ProxyPassReverse        /testazure              http://localhost:8080
```
And I made some changes in the templates of the example to redirect the auth_page.html and index.html forms to /testazure/msal4jsample/XXX.

Also I changed the application.properties file to redirect to my Apache, that works in https:
```
aad.redirectUriSignin=https://localhost/testazure/msal4jsample/secure/aad
aad.redirectUriGraph=https://localhost/testazure/msal4jsample/graph/me
```

When I access to https://localhost/testazure, it shows me the website:
![image](https://user-images.githubusercontent.com/4680243/112487596-24a2a780-8d7d-11eb-9e34-c6a33a865592.png)

When I try to login, it ask me about the user, but when I choose my user, the server throws this exception:
```
2021-03-25 15:06:09.018 ERROR 77186 --- [onPool-worker-2] c.m.a.m.ConfidentialClientApplication    : [Correlation ID: a3857c1b-8c7f-4aaf-9df3-7d0092a9d900] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.

com.microsoft.aad.msal4j.MsalServiceException: AADSTS500112: The reply address 'http://localhost:8080/msal4jsample/secure/aad' does not match the reply address 'https://localhost/testazure/msal4jsample/secure/aad' provided when requesting Authorization code.
Trace ID: 7b151e82-b7c1-46c8-a237-e9875a079500
Correlation ID: a3857c1b-8c7f-4aaf-9df3-7d0092a9d900
Timestamp: 2021-03-25 14:06:08Z
	at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:43) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:90) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:38) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:117) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59) [msal4j-1.6.1.jar:1.6.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17) [msal4j-1.6.1.jar:1.6.1]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604) [na:1.8.0_281]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [na:1.8.0_281]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_281]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) [na:1.8.0_281]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) [na:1.8.0_281]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) [na:1.8.0_281]
```

If I change in AuthFilter.java file the currentUri attribute to the following value, it works:
```
currentUri = "https://localhost/testazure" + httpRequest.getRequestURI();
```

Does exist any way to configure it to work without doing that?

**Comment by Avery-Dunn** [comment]
Hello @marcgise : You set the redirect URIs in applications.properties, but did you also set them in the app registration in Azure? 

Check the 'authentication' tab of your app in Azure (like in the below image), it may still have the default redirect URIs which are missing the /testazure part needed by your client application. I haven't used ProxyPass before, but if all that's needed is for requests to have that /testazure path in it then having the correct redirect URLs should be enough. 

If it's still not working or if the redirect URLs are already correct, then you may have to use your own HTTPClient class to handle any extra HTTP steps ([see here](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Configure-Http-Client) for more info on overriding the library's default HTTP stuff)

![image](https://user-images.githubusercontent.com/62066438/112540962-0a160180-8d70-11eb-973c-206217626b30.png)
