### ISSUE TITLE
Not getting access token

### ISSUE THREAD

**Issue by hemant7737** [AzureAD/microsoft-authentication-library-for-java#413]
Configured MSAL4J in my Java App to authenticate AD B2C user and acquiring token using auth code flow. Authentication works fine but not getting access token in the response.

Using Confidential client applications and acquire tokens by authorization code after letting the user sign-in through the authorization request URL.

Getting below error.

```
com.microsoft.aad.msal4j.MsalClientException: Invalid or missing token, could not parse. If using B2C, information on a potential B2C issue and workaround can be found here: https://aka.ms/msal4j-b2c-known-issues
	at com.microsoft.aad.msal4j.TokenResponse.parseJsonObject(TokenResponse.java:85) ~[msal4j-1.10.1.jar:1.10.1]
	at com.microsoft.aad.msal4j.TokenResponse.parseHttpResponse(TokenResponse.java:36) ~[msal4j-1.10.1.jar:1.10.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:67) ~[msal4j-1.10.1.jar:1.10.1]
	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:37) ~[msal4j-1.10.1.jar:1.10.1]
	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128) ~[msal4j-1.10.1.jar:1.10.1]
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63) ~[msal4j-1.10.1.jar:1.10.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59) ~[msal4j-1.10.1.jar:1.10.1]
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17) ~[msal4j-1.10.1.jar:1.10.1]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]

```
Would like to pay thanks in advance for any resolution.

**Comment by sangonzal** [comment]
Hi @hemant7737, did you visit the link included in the error message? (https://aka.ms/msal4j-b2c-known-issues)

You'll have to include your application id as one of the scopes. The issue and the workaround are explained in the link that is shared in the error message.

**Comment by hemant7737** [comment]
Hi @sangonzal , 

Have tried with the approach that you mentioned but still no difference. 
Although I have downloaded the sample provide on the repository. Could you please help me with any reference where it is working fine?

**Comment by sangonzal** [comment]
@hemant7737 There is no sample showing this. It should be as simple as just passing in your ClientId to the scope parameter. For example, something along the lines of: 

```
            Set<String> scope = Collections.singleton(clientId); 
            SilentParameters silentParameters =
                    SilentParameters
                            .builder(scope)
                            .account(account)
                            .build();
```

If this is still not working for you, could you please share your code and a fiddler trace? Instructions on how to do this: https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Fiddler
