### ISSUE TITLE
Unable to Integrate msal4j api : NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes

### ISSUE THREAD

**Issue by anilkumarhgowda** [AzureAD/microsoft-authentication-library-for-java#414]
Hi Team,

**We are trying to integrate MSAL4J APIs with our Application to implement the https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-web-app-call-api-app-configuration?tabs=aspnetcore#client-secrets-or-client-certificates authorization mechanism,  but we are facing jar conflict issues with our existing key-vault jar. Below is the error log. Kindly help us in resolving the issue.**

**Error logs :** 
2021-07-08 16:45:35.862 ERROR [-,,,] 10580 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: **Failed to configure KeyVault property source**
              at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:75) ~[azure-spring-boot-2.1.2.jar:na]
              at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessor.postProcessEnvironment(KeyVaultEnvironmentPostProcessor.java:26) ~[azure-spring-boot-2.1.2.jar:na]
              at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:177) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
              at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:163) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
              at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
              at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
              at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
              at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
              at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
              at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
              at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
              at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
              at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
              at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
              at com.cbre.host.auth.HostAuthApplication.main(HostAuthApplication.java:25) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Failed to do authentication.
              at com.microsoft.azure.keyvault.spring.AzureKeyVaultCredential.doAuthenticate(AzureKeyVaultCredential.java:48) ~[azure-spring-boot-2.1.2.jar:na]
              at com.microsoft.azure.keyvault.authentication.KeyVaultCredentials.doAuthenticate(KeyVaultCredentials.java:417) ~[azure-keyvault-1.2.1.jar:1.2.1]
              at com.microsoft.azure.keyvault.authentication.KeyVaultCredentials.getAuthenticationCredentials(KeyVaultCredentials.java:221) ~[azure-keyvault-1.2.1.jar:1.2.1]
              at com.microsoft.azure.keyvault.authentication.KeyVaultCredentials.buildAuthenticatedRequest(KeyVaultCredentials.java:120) ~[azure-keyvault-1.2.1.jar:1.2.1]
              at com.microsoft.azure.keyvault.authentication.KeyVaultCredentials.buildAuthenticatedRequest(KeyVaultCredentials.java:158) ~[azure-keyvault-1.2.1.jar:1.2.1]
              at com.microsoft.azure.keyvault.authentication.KeyVaultCredentials.access$300(KeyVaultCredentials.java:34) ~[azure-keyvault-1.2.1.jar:1.2.1]
              at com.microsoft.azure.keyvault.authentication.KeyVaultCredentials$1.intercept(KeyVaultCredentials.java:76) ~[azure-keyvault-1.2.1.jar:1.2.1]
              at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar:na]
              at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar:na]
              at com.microsoft.rest.interceptors.BaseUrlHandler.intercept(BaseUrlHandler.java:43) ~[client-runtime-1.6.0.jar:na]
              at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar:na]
              at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar:na]
              at com.microsoft.rest.interceptors.RequestIdHeaderInterceptor.intercept(RequestIdHeaderInterceptor.java:29) ~[client-runtime-1.6.0.jar:na]
              at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.8.1.jar:na]
              at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.8.1.jar:na]
              at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) ~[okhttp-3.8.1.jar:na]
              at okhttp3.RealCall.execute(RealCall.java:69) ~[okhttp-3.8.1.jar:na]
              at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) ~[retrofit-2.4.0.jar:na]
              at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40) ~[adapter-rxjava-2.4.0.jar:na]
              at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24) ~[adapter-rxjava-2.4.0.jar:na]
              at rx.Observable.unsafeSubscribe(Observable.java:10327) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.Observable.subscribe(Observable.java:10423) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.Observable.subscribe(Observable.java:10390) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:443) ~[rxjava-1.3.8.jar:1.3.8]
              at rx.observables.BlockingObservable.single(BlockingObservable.java:340) ~[rxjava-1.3.8.jar:1.3.8]
              at com.microsoft.azure.keyvault.implementation.KeyVaultClientBaseImpl.getSecrets(KeyVaultClientBaseImpl.java:3922) ~[azure-keyvault-1.2.1.jar:1.2.1]
              at com.microsoft.azure.keyvault.implementation.KeyVaultClientCustomImpl.listSecrets(KeyVaultClientCustomImpl.java:1170) ~[azure-keyvault-1.2.1.jar:1.2.1]
              at com.microsoft.azure.keyvault.spring.KeyVaultOperation.createOrUpdateHashMap(KeyVaultOperation.java:88) ~[azure-spring-boot-2.1.2.jar:na]
              at com.microsoft.azure.keyvault.spring.KeyVaultOperation.<init>(KeyVaultOperation.java:43) ~[azure-spring-boot-2.1.2.jar:na]
              at com.microsoft.azure.keyvault.spring.KeyVaultEnvironmentPostProcessorHelper.addKeyVaultPropertySource(KeyVaultEnvironmentPostProcessorHelper.java:65) ~[azure-spring-boot-2.1.2.jar:na]
              ... 14 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
              at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
              at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[na:na]
              at com.microsoft.azure.keyvault.spring.AzureKeyVaultCredential.doAuthenticate(AzureKeyVaultCredential.java:45) ~[azure-spring-boot-2.1.2.jar:na]
              ... 49 common frames omitted
Caused by: java.lang.NoClassDefFoundError: **com/nimbusds/oauth2/sdk/http/CommonContentTypes**
              at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:157) ~[adal4j-1.6.0.jar:1.6.0]
              at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85) ~[adal4j-1.6.0.jar:1.6.0]
              at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928) ~[adal4j-1.6.0.jar:1.6.0]
              at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.0.jar:1.6.0]
              at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.0.jar:1.6.0]
              at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.0.jar:1.6.0]
              at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
              at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
              at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
              at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.ClassNotFoundException: com.nimbusds.oauth2.sdk.http.CommonContentTypes
              at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
              at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
              at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
              ... 10 common frames omitted

**Here is a snapshot of our pom.xml with the current jars used:**

<project xmlns=http://maven.apache.org/POM/4.0.0
              xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance
              xsi:schemaLocation=http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd>
              <modelVersion>1.0.0</modelVersion>
              <groupId>com.xyz.abc.uk</groupId>
              <artifactId>com.xyz.abc.uk</artifactId>
              <packaging>jar</packaging>
              <name>xyz-abc-uk</name>
              <version>1.0.0-SNAPSHOT</version>
              <properties>
                             <java.version>11</java.version>
                             <sonar.host.url>https://xyz.com</sonar.host.url>
                             <sonar.projectKey>xyz</sonar.projectKey>
                             <sonar.sources>src/main/java</sonar.sources>
                             <azure.version>2.1.2</azure.version>
                             <spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
                             <springfox-swagger.version>2.9.2</springfox-swagger.version>
              </properties>
              <parent>
                             <groupId>org.springframework.boot</groupId>
                             <artifactId>spring-boot-starter-parent</artifactId>
                             <version>2.1.3.RELEASE</version>
              </parent>

              

              <dependencies>
                             
                             <dependency>
                                           <groupId>org.springframework.boot</groupId>
                                           <artifactId>spring-boot-starter-web</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>org.springframework.security.oauth</groupId>
                                           <artifactId>spring-security-oauth2</artifactId>
                                           <version>2.3.3.RELEASE</version>
                             </dependency>
                             <dependency>
                                           <groupId>com.microsoft.azure</groupId>
                                           <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
                             </dependency> 
              
                             <dependency>
                                           <groupId>org.springframework.cloud</groupId>
                                           <artifactId>spring-cloud-starter-zipkin</artifactId>
                             </dependency>

                             <dependency>
                                           <groupId>org.springframework.cloud</groupId>
                                           <artifactId>spring-cloud-sleuth-zipkin</artifactId>
                             </dependency>

                             
                             <dependency>
                                           <groupId>org.springframework.boot</groupId>
                                           <artifactId>spring-boot-starter-actuator</artifactId>
                             </dependency>

                             <dependency>
                                           <groupId>org.springframework.boot</groupId>
                                           <artifactId>spring-boot-starter-test</artifactId>
                                           <scope>test</scope>
                             </dependency>
                             <dependency>
                                           <groupId>org.springframework</groupId>
                                           <artifactId>spring-test</artifactId>
                                           <scope>test</scope>
                             </dependency>
                             <dependency>
                                           <groupId>org.springframework.boot</groupId>
                                           <artifactId>spring-boot-test</artifactId>
                                           <scope>test</scope>
                             </dependency>
                             <dependency>
                                           <groupId>org.springframework.boot</groupId>
                                           <artifactId>spring-boot-configuration-processor</artifactId>
                                          <optional>true</optional>
                             </dependency>
                             <dependency>
                                           <groupId>org.apache.commons</groupId>
                                           <artifactId>commons-lang3</artifactId>
                                           <version>3.8.1</version>
                             </dependency>
                             <dependency>
                                           <groupId>org.apache.commons</groupId>
                                           <artifactId>commons-text</artifactId>
                                           <version>1.9</version>
                             </dependency>
                             <dependency>
                                           <groupId>com.microsoft.azure</groupId>
                                           <artifactId>azure-active-directory-spring-boot-starter</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>org.projectlombok</groupId>
                                           <artifactId>lombok</artifactId>
                                           <optional>true</optional>
                             </dependency>
                             <dependency>
                                           <groupId>org.json</groupId>
                                           <artifactId>json</artifactId>
                                           <version>20180813</version>
                             </dependency>
                             <dependency>
                                           <groupId>io.springfox</groupId>
                                           <artifactId>springfox-swagger2</artifactId>
                                           <version>${springfox-swagger.version}</version>
                             </dependency>
                             <dependency>
                                           <groupId>io.springfox</groupId>
                                           <artifactId>springfox-swagger-ui</artifactId>
                                           <version>${springfox-swagger.version}</version>
                             </dependency>
                             <dependency>
                                           <groupId>junit</groupId>
                                           <artifactId>junit</artifactId>
                                           <scope>test</scope>
                             </dependency>

                             
                             <dependency>
                                           <groupId>com.google.googlejavaformat</groupId>
                                           <artifactId>google-java-format</artifactId>
                                           <version>1.6</version>
                             </dependency>

                             <dependency>
                                           <groupId>javax.xml.bind</groupId>
                                           <artifactId>jaxb-api</artifactId>
                                           <version>2.3.1</version>
                             </dependency>

                             <dependency>
                                           <groupId>org.apache.httpcomponents</groupId>
                                           <artifactId>httpclient</artifactId>
                                           <version>4.5.7</version>
                             </dependency>

                             <dependency>
                                           <groupId>redis.clients</groupId>
                                           <artifactId>jedis</artifactId>
                             </dependency>
                             <dependency>
                                           <groupId>org.springframework.data</groupId>
                                           <artifactId>spring-data-redis</artifactId>
                             </dependency>

                             <dependency>
                                           <groupId>io.github.resilience4j</groupId>
                                           <artifactId>resilience4j-retry</artifactId>
                                           <version>1.3.1</version>
                             </dependency>
                             <dependency>
                                           <groupId>io.github.resilience4j</groupId>
                                           <artifactId>resilience4j-spring-boot2</artifactId>
                                           <version>1.3.1</version>
                             </dependency>
                             
                <dependency>
                                           <groupId>com.microsoft.azure</groupId>
                                           <artifactId>msal4j</artifactId>
                                           <version>1.6.2</version>
                             </dependency> 
                             <dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>oauth2-oidc-sdk</artifactId>
    <version>9.7</version>
</dependency>
              </dependencies>

              <dependencyManagement>
                             <dependencies>
                                           <dependency>
                                                         <groupId>org.springframework.cloud</groupId>
                                                          <artifactId>spring-cloud-dependencies</artifactId>
                                                          <version>${spring-cloud.version}</version>
                                                          <type>pom</type>
                                                          <scope>import</scope>
                                           </dependency>
                                           <dependency>
                                                          <groupId>com.microsoft.azure</groupId>
                                                          <artifactId>azure-spring-boot-bom</artifactId>
                                                          <version>${azure.version}</version>
                                                          <type>pom</type>
                                                          <scope>import</scope>
                                           </dependency>
                             </dependencies>
              </dependencyManagement>

              <build>
                             <plugins>
                                           <plugin>
                                                         <groupId>org.springframework.boot</groupId>
                                                          <artifactId>spring-boot-maven-plugin</artifactId>
                                           </plugin>
                                           <plugin>
                                                          <groupId>org.jacoco</groupId>
                                                          <artifactId>jacoco-maven-plugin</artifactId>
                                                          <version>0.8.3</version>
                                                          <executions>
                                                                        <execution>
                                                                                      <id>default-prepare-agent</id>
                                                                                      <goals>
                                                                                                     <goal>prepare-agent</goal>
                                                                                      </goals>
                                                                        </execution>
                                                                        <execution>
                                                                                      <id>default-report</id>
                                                                                      <phase>prepare-package</phase>
                                                                                      <goals>
                                                                                                    <goal>report</goal>
                                                                                      </goals>
                                                                        </execution>
                                                          </executions>
                                           </plugin>
                             </plugins>
              </build>

</project>

Thank you
Anilkumar

**Comment by Avery-Dunn** [comment]
Hello @anilkumarhgowda : I noticed in your error log this line:
`Caused by: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:157) ~[adal4j-1.6.0.jar:1.6.0]`

It looks like you're using an old version of [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-java/tree/1.6.7) Java (version 1.6), which we're deprecating, rather than MSAL, which is what this repository is for. Is that intentional? Do you have some reason for using ADAL instead of MSAL? 

I'd recommend trying to use [MSAL](https://mvnrepository.com/artifact/com.microsoft.azure/msal4j), or at the very least try the latest version of ADAL ([1.6.7](https://github.com/AzureAD/azure-activedirectory-library-for-java/releases/tag/1.6.7)), that might solve these dependency problems you're having.

**Comment by anilkumarhgowda** [comment]
Hi Team, 

I appreciate your quick response, we are trying integrate **https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-java-webapp** sample with our application.

I have added below two dependency as suggested in the above sample link.
 <dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>msal4j</artifactId>
	<version>1.6.1</version>
 </dependency> 
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>oauth2-oidc-sdk</artifactId>
    <version>6.5</version>
</dependency>


**Note : We are using this with key vault 
 <dependency>
         <groupId>com.microsoft.azure</groupId>
         <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
         <version>2.1.2</version>**
 </dependency> 

as suggested, I have done the testing with updated version. still facing same issue again, I have added complete pom.xml file in previous comments.


<dependency>
	<groupId>com.microsoft.azure</groupId>
	<artifactId>msal4j</artifactId>
	<version>1.10.1</version>
 </dependency> 
     and   
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>oauth2-oidc-sdk</artifactId>
    <version>9.9</version>
</dependency>


**Error Log: getting from nimbusds/oauth2/sdk
Caused by: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
 at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:157) ~[adal4j-1.6.0.jar:1.6.0]**

If I comment below depenadncy

<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>oauth2-oidc-sdk</artifactId>
    <version>9.9</version>
</dependency>



**I am getting compile error as show in image.**

![image](https://user-images.githubusercontent.com/46807235/125042512-8b8f6680-e0b7-11eb-9a34-da3467587550.png)

Please can you help me to solve dependency conflict issue ASAP,  I will be waiting for your response.

Thank you
Anilkumar

**Comment by Avery-Dunn** [comment]
@anilkumarhgowda : Ah, I think I understand the issue now. That error message you posted in still showing that 'adal4j-1.6.0' is what's throwing the error, despite you using MSAL. This is because the version of 'azure-keyvault-secrets-spring-boot-starter' you're using, [2.1.2](https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault-secrets-spring-boot-starter/2.1.2), uses ADAL as a dependency.

In order to fix this, you'd either need to use a version of oauth2-oidc-sdk that ADAL 1.6.0 uses (5.24.1, but this is not recommended due to various security issues that whoever develops oauth2-oidc-sdk has fixed over the years), or upgrade azure-keyvault-secrets-spring-boot-starter to a version that uses newer versions of MSAL that are compatible with newer versions of oauth2-oidc-sdk.

A quick look at the maven dependencies shows that azure-keyvault-secrets-spring-boot-starter stopped using ADAL directly as of [2.2.3](https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault-secrets-spring-boot-starter/2.2.3), but [one of their dependencies](https://mvnrepository.com/artifact/com.microsoft.azure/azure-client-authentication/1.7.13) still does so there's a chance you'd run into the same problem. As of version [2.3.3](https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault-secrets-spring-boot-starter/2.3.3) they start using dependencies that use MSAL, so that version or anything after that should work. It also looks like they moved development of that artifact to [azure-spring-boot-starter-keyvault-secrets](https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-starter-keyvault-secrets), so you may want to start using that dependency instead.

**Comment by Avery-Dunn** [comment]
Closing due to inactivity. If you're still having issues or have any related questions, feel free to reopen this thread.
