### ISSUE TITLE
getAccounts throws NullPointerException after acquiring token

### ISSUE THREAD

**Issue by TotallyNotASecret** [AzureAD/microsoft-authentication-library-for-java#439]
Running the sample code at https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/src/samples/public-client/UsernamePasswordFlow.java, NullPointerException is thrown at line 44, after acquiring a token using username and password. This also happened trying to to use the getAccounts function in my own code.

I am working with ADFS 2019.

Recreating the exception:

```
PublicClientApplication pca = PublicClientApplication
                .builder("clientid")
                .authority("authority")
                .build();
Set<String> scopes = Set.of("openid");
UserNamePasswordParameters params = UserNamePasswordParameters
                .builder(scopes, "username@domain.com", "password".toCharArray())
                .build();
pca.getAccounts.join(); // Works.
pca.acquireToken(params).join();
pca.getAccounts.join(); // Crashes.
```

**Comment by Avery-Dunn** [comment]
Hello @TotallyNotASecret : I just tried that code with an ADFS 2019 account and didn't encounter a null pointer exception, everything worked fine. Could you post the full error that you're getting?

**Comment by TotallyNotASecret** [comment]
@Avery-Dunn thanks for the quick response.
The full error is
```
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.NullPointerException
        at com.microsoft.aad.msal4j.AccountSupplier.get(AccountSupplier.java:33)
        at com.microsoft.aad.msal4j.AccountSupplier.get(AccountSupplier.java:11)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupplier.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupplier.exec(CompletableFuture.java:1692)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
        at java.base/java.lang.String.contains(String.java:2036)
        at com.microsoft.aad.msal4j.TokenCache.getAccounts(TokenCache.java:348)
        at com.microsoft.aad.msal4j.AccountsSupplier.get(AccountsSupplier.java:26)
        ... 8 more   
```
After more testing and debugging, it seems the root cause of this error is in the `TokenCache` (https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/v1.11.0/src/main/java/com/microsoft/aad/msal4j/TokenCache.java) and `AccountCacheEntity` (https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/v1.11.0/src/main/java/com/microsoft/aad/msal4j/AccountCacheEntity.java) classes.
In `TokenCache.getAccounts`, there is the following check on line 348: 
```
if (accCached.homeAccountId().contains(accCached.localAccountId()))
```
but `accCached.localAccountId()` is null in my case, which is why `String.contains` throws `NullPointerException`.
After looking at `AccountCacheEntity`, I noticed the function to create a new ADFS account does not set some of the properties that the Azure create does, including `localAccountId` and `realm`. Here are both functions (lines 66-100):
```
static AccountCacheEntity create(String clientInfoStr, Authority requestAuthority, IdToken idToken, String policy) {

        AccountCacheEntity account = new AccountCacheEntity();
        account.authorityType(MSSTS_ACCOUNT_TYPE);
        account.clientInfoStr = clientInfoStr;
        account.homeAccountId(policy != null ?
                account.clientInfo().toAccountIdentifier() + Constants.CACHE_KEY_SEPARATOR + policy :
                account.clientInfo().toAccountIdentifier());
        account.environment(requestAuthority.host());
        account.realm(requestAuthority.tenant());

        if (idToken != null) {
            String localAccountId = !StringHelper.isBlank(idToken.objectIdentifier)
                    ? idToken.objectIdentifier : idToken.subject;
            account.localAccountId(localAccountId);
            account.username(idToken.preferredUsername);
            account.name(idToken.name);
        }

        return account;
    }

    static AccountCacheEntity createADFSAccount(Authority requestAuthority, IdToken idToken) {

        AccountCacheEntity account = new AccountCacheEntity();
        account.authorityType(ADFS_ACCOUNT_TYPE);
        account.homeAccountId(idToken.subject);

        account.environment(requestAuthority.host());

        account.username(idToken.upn);
        account.name(idToken.uniqueName);

        return account;
    }
```
To me that looks like the root cause of the bug. I don't know why you didn't encounter the bug, since I can't get this to work in any way. Thanks for the help!
