### ISSUE TITLE
What is the scopes parameter MSAL for Java classes require? help!!!!

### ISSUE THREAD

**Issue by xiangli425** [AzureAD/microsoft-authentication-library-for-java#490]
What's the relationship between resourcetype and scope?
I had writen in this way.:
`> Set<String> scopes = Collections.singleton(resourceType.replaceAll("/\\z", "") + "//.default");`

**As a result, I received a fatal error!!!**

**Comment by siddhijain** [comment]
Hey @xiangli425 Can you please provide more details? What is a resource type here? A scope is not related to resourceType.
Here are some documents on scope - 
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-v1-app-scopes
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/scopes.md
https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-adal-msal-java#:~:text=A%20number%20of%20MSAL%20for%20Java%20classes%20require,migrate%20your%20apps%20from%20the%20ADAL%20to%20MSAL.

Let me know if that solves your issue.

**Comment by xiangli425** [comment]
> Hey @xiangli425 Can you please provide more details? What is a resource type here? A scope is not related to resourceType. Here are some documents on scope - https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-v1-app-scopes https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/scopes.md https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-adal-msal-java#:~:text=A%20number%20of%20MSAL%20for%20Java%20classes%20require,migrate%20your%20apps%20from%20the%20ADAL%20to%20MSAL.
> 
> Let me know if that solves your issue.

this are my codes, I just don't know what the scopes in msal should be 
`adal:
AsymmetricKeyCredential cred = AsymmetricKeyCredential.create(clientId, new ByteArrayInputStream(pkcs12Secret), "");
            AuthenticationContext context = new AuthenticationContext(stsurl, false, Executors.newFixedThreadPool(1));
            Future<AuthenticationResult> future = context.acquireToken(resourceType, cred, null);
            return future.get().getAccessToken();

msal:
Set<String> scopes = Collections.singleton(resourceType.replaceAll("/\\z", "") + "//.default");
            IClientCredential credential = ClientCredentialFactory.createFromSecret(new ByteArrayInputStream(pkcs12Secret).toString());
            ConfidentialClientApplication cca =
                    ConfidentialClientApplication
                            .builder(clientId, credential)
                            .authority(stsurl)
                            .build();

            ClientCredentialParameters parameters =
                    ClientCredentialParameters
                            .builder(scopes)
                            .build();
            return cca.acquireToken(parameters).join().accessToken();`

**Comment by siddhijain** [comment]
Hello @xiangli425 , You can add the /.default scope suffix to the resource to help migrate your apps from the ADAL to MSAL. For example, for the resource value of https://graph.microsoft.com, the equivalent scope value is https://graph.microsoft.com/.default
So in your case, instead of 
Set scopes = Collections.singleton(resourceType.replaceAll("/\z", "") + "//.default");
You can do
Collections.singleton(resourceType + "/.default"); OR Collections.singleton(resourceType.append("/.default"));

**Comment by xiangli425** [comment]
here is the information of error logs:
2022-04-12 07:41:02.520Z [pool-6-thread-1] ERROR c.m.p.l.moderate.KenshoLogger2#outputDevLog[136] - [DEVLOG] [IngestionComm] Error. [Kusto data fetch] Get access token failed. | EXCEPTION: com.microsoft.aad.msal4j.MsalServiceException: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '67862165-cbdc-4811-bb83-d6d945a98b6b'.
Trace ID: 6180d978-6247-4ecf-89e4-6dbea09ebf00
Correlation ID: c73874d2-f1da-4fd2-b755-e6540d459a41
Timestamp: 2022-04-12 07:41:02Z
java.util.concurrent.CompletionException: com.microsoft.aad.msal4j.MsalServiceException: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '67862165-cbdc-4811-bb83-d6d945a98b6b'.
Trace ID: 6180d978-6247-4ecf-89e4-6dbea09ebf00
Correlation ID: c73874d2-f1da-4fd2-b755-e6540d459a41
Timestamp: 2022-04-12 07:41:02Z
at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:101)
at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:20)
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
at java.lang.Thread.run(Thread.java:750)
Caused by: com.microsoft.aad.msal4j.MsalServiceException: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '67862165-cbdc-4811-bb83-d6d945a98b6b'.
Trace ID: 6180d978-6247-4ecf-89e4-6dbea09ebf00
Correlation ID: c73874d2-f1da-4fd2-b755-e6540d459a41
Timestamp: 2022-04-12 07:41:02Z
at com.microsoft.aad.msal4j.MsalServiceExceptionFactory.fromHttpResponse(MsalServiceExceptionFactory.java:45)
at com.microsoft.aad.msal4j.TokenRequestExecutor.createAuthenticationResultFromOauthHttpResponse(TokenRequestExecutor.java:102)
at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:37)
at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128)
at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:63)
at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49)
at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:71)
... 3 common frames omitted

**Comment by siddhijain** [comment]
It looks like the client_secret provided is invalid. Make sure you are using secret_value and not secret_ID from the azure portal. [![Secret_value](https://user-images.githubusercontent.com/30181294/163830492-8aad5a1d-bf6f-4c20-990c-6b27c23f1d4d.png)(url)

**Comment by siddhijain** [comment]
Since msal is all scope based, different tokens are needed for different resource+scope. When the user requested different tokens 1 for each resource, the issue got resolved. 
Closing since resolved.
