### ISSUE TITLE
java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by sergiocondeco** [AzureAD/microsoft-authentication-library-for-java#561]
Hello everyone. I'm trying to get an access token with msal. Here's my code:

ConfidentialClientApplication app = ConfidentialClientApplication.builder(
	                clientId,
	                ClientCredentialFactory.createFromSecret(secretId))
	                .authority(authority)
	                .build();   

	        Set<String> scopes = new HashSet<String>();
	        scopes.add(scope);
	        ClientCredentialParameters clientCredentialParam = ClientCredentialParameters.builder(
	                scopes)
	                .build();
	        
	        CompletableFuture<IAuthenticationResult> future = app.acquireToken(clientCredentialParam);
	        IAuthenticationResult result = future.get();
	        accessToken = result.accessToken();

I'm getting an error at line  IAuthenticationResult result = future.get();

java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
     [java] 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
     [java] 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)

Any idea what i'm doing wrong? Thanks in advance.

**Comment by sergiocondeco** [comment]
All stack:
java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
     [java] 	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
     [java] 	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
     [java] 	at apdp.podologia.ficha.logic.ImportacaoImagensLogic.getAccessTokenByClientCredentialGrant(ImportacaoImagensLogic.java:243)
     [java] 	at apdp.podologia.ficha.logic.ImportacaoImagensLogic.importar(ImportacaoImagensLogic.java:128)
     [java] 	at apdp.podologia.ficha.logic.ImportacaoImagensLogic.main(ImportacaoImagensLogic.java:75)
     [java] Caused by: java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
     [java] 	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:88)
     [java] 	at com.microsoft.aad.msal4j.TokenRequestExecutor.createOauthHttpRequest(TokenRequestExecutor.java:53)
     [java] 	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:31)
     [java] 	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128)
     [java] 	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
     [java] 	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:63)
     [java] 	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49)
     [java] 	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:71)
     [java] 	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:20)
     [java] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
     [java] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
     [java] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
     [java] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
     [java] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
     [java] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
     [java] 10:22:35.789 (ForkJoinPool.commonPool-worker-9) DEBUG [com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier] - Cache lookup failed: Token not found in the cache
     [java] 10:22:35.795 (ForkJoinPool.commonPool-worker-9) ERROR [com.microsoft.aad.msal4j.ConfidentialClientApplication] - [Correlation ID: ea255454-9afb-4408-b083-3dd602364e3f] Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed.
     [java] java.lang.ClassCastException: java.util.Collections$SingletonList cannot be cast to java.lang.String
     [java] 	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:88)
     [java] 	at com.microsoft.aad.msal4j.TokenRequestExecutor.createOauthHttpRequest(TokenRequestExecutor.java:53)
     [java] 	at com.microsoft.aad.msal4j.TokenRequestExecutor.executeTokenRequest(TokenRequestExecutor.java:31)
     [java] 	at com.microsoft.aad.msal4j.AbstractClientApplicationBase.acquireTokenCommon(AbstractClientApplicationBase.java:128)
     [java] 	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:63)
     [java] 	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:63)
     [java] 	at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49)
     [java] 	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:71)
     [java] 	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:20)
     [java] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
     [java] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
     [java] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
     [java] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
     [java] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
     [java] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
