### ISSUE TITLE
msal4j build / package failure

### ISSUE THREAD

**Issue by cubesnyc** [AzureAD/microsoft-authentication-library-for-java#866]
Java version 8.0.422-amzn
Maven version 3.9.9

Attempting to package msal4j according to these instructions: 
https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Maven

Reproducible example:
```
//any other version than 8 results in an error
//11 results in javadoc errors regarding unnamed modules
//17+ results in lombok errors
sdk install java 8.0.422-amzn

brew install maven

git clone https://github.com/AzureAD/microsoft-authentication-library-for-java.git
cd microsoft-authentication-library-for-java
mvn clean
mvn package
```

the result is:
[INFO] msal4j 1.17.2 ...................................... SUCCESS [  6.707 s]
[INFO] msal4j-brokers 1.0.0 ............................... SUCCESS [  2.055 s]
[INFO] msal4j-persistence-extension 1.3.0 ................. FAILURE [ 10.406 s]
[INFO] microsoft-authentication-library-for-java 1.0.0 .... SKIPPED

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project msal4j-persistence-extension: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/yyurgenson/IdeaProjects/microsoft-authentication-library-for-java/msal4j-persistence-extension/target/surefire-reports for the individual test results.

the logs detail this error stacktrace:
-------------------------------------------------------------------------------
Test set: com.microsoft.aad.msal4jextensions.CacheAccessorTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.235 sec <<< FAILURE!
keyChainIOTest(com.microsoft.aad.msal4jextensions.CacheAccessorTest)  Time elapsed: 0.202 sec  <<< ERROR!
com.microsoft.aad.msal4jextensions.persistence.CacheFileAccessException: Failed to set lastModified time on Cache File
	at com.microsoft.aad.msal4jextensions.persistence.CacheFileAccessor.updateCacheFileLastModifiedTime(CacheFileAccessor.java:108)
	at com.microsoft.aad.msal4jextensions.persistence.mac.KeyChainAccessor.delete(KeyChainAccessor.java:136)
	at com.microsoft.aad.msal4jextensions.CacheAccessorTest.readWriteTest(CacheAccessorTest.java:88)
	at com.microsoft.aad.msal4jextensions.CacheAccessorTest.keyChainIOTest(CacheAccessorTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: java.nio.file.NoSuchFileException: /Users/rootuser/test.cache
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixPath.openForAttributeAccess(UnixPath.java:787)
	at sun.nio.fs.UnixFileAttributeViews$Basic.setTimes(UnixFileAttributeViews.java:74)
	at java.nio.file.Files.setLastModifiedTime(Files.java:2306)
	at com.microsoft.aad.msal4jextensions.persistence.CacheFileAccessor.updateCacheFileLastModifiedTime(CacheFileAccessor.java:106)
	... 36 more

manually creating the test.cache file doesnt work, as something in the tests seems to delete it.

**Comment by Avery-Dunn** [comment]
Hello @cubesnyc : I'm not able to reproduce your issue myself, and our tests often have extra internal steps that may cause them to fail outside of our dev environments. Since the tests for the msal4j package only took 6.7 seconds, it's clear that none of them ran (the full integration and unit tests take ~10 minutes to run) so I'm not sure why that didn't also fail.

Regardless, why are you trying to build the MSAL libraries yourselfrather than getting the packages from Maven?
- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j
- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j-brokers
- https://mvnrepository.com/artifact/com.microsoft.azure/msal4j-persistence-extension

If you truly need to build test locally for some reason, I'd recommend either skipping the tests (-Dmaven.test.skip=true in your mvn command), or removing the msal4j-persistence-extension 1.3.0 module from the [parent pom.xml](https://github.com/AzureAD/microsoft-authentication-library-for-java/blob/dev/pom.xml) if you don't plan on actually using that package.

**Comment by Avery-Dunn** [comment]
Closing due to inactivity. If you're still having issues or have any other questions feel free to re-open this thread or start a new one.
