### ISSUE TITLE
Server returned HTTP response code: 401

### ISSUE THREAD

**Issue by mion1985** [AzureAD/microsoft-authentication-library-for-java#91]
I followed the instructions from this site https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Integrated-Windows-Authentication
Unfortunately I'm getting 401 response code with this exception:
```
[ForkJoinPool.commonPool-worker-1] ERROR com.microsoft.aad.msal4j.PublicClientApplication - [Correlation ID: xxx] Execution of class com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier failed.
com.microsoft.aad.msal4j.MsalServiceException: Server returned HTTP response code: 401 for URL : https://adfs.{company_name}.com/adfs/services/trust/2005/windowstransport
	at com.microsoft.aad.msal4j.HttpHelper.readResponseFromConnection(HttpHelper.java:164)
	at com.microsoft.aad.msal4j.HttpHelper.getResponse(HttpHelper.java:91)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpPost(HttpHelper.java:78)
	at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:47)
	at com.microsoft.aad.msal4j.WSTrustRequest.execute(WSTrustRequest.java:52)
	at com.microsoft.aad.msal4j.WSTrustRequest.execute(WSTrustRequest.java:101)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.getAuthorizationGrantIntegrated(AcquireTokenByAuthorizationGrantSupplier.java:126)
	at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:40)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:57)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
I've checked the user, scope, clientId and authorization and they are correct.
When I run C# example with the same user, scope, clientId and authorization everything works fine.

What can be a reason of this problem ?

**Comment by sangonzal** [comment]
@mion1985 In MSAL Java, Integrated Windows Authentication (IWA) works by using Kerberos under the hood. This means that Kerberos must be set up correctly in your domain and there must be able to obtain Kerberos tickets for the user trying to authenticate.

 I would suggest running the [Kinit](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/kinit.html) tool to obtain a Kerberos ticket, and if that works, run IWA again and see if you can acquire a token. 

To run Kinit, open up a command prompt, navigate to the bin folder of your JDK, and type "kinit user@domain.com". This should prompt you for password, and then obtain and cache a Kerberos ticket.

**Comment by mion1985** [comment]
when I run kinit there is no problem:
```
Password for {user}@{domain}:
New ticket is stored in cache file C:\Users\user\{somecode_user}
```
Should I somehow initialize kerberos from my code ?

**Comment by sangonzal** [comment]
Yes,  you should be able to get a kerberos ticket programmatically

**Comment by sangonzal** [comment]
@mion1985 I'm going to close this, feel free to reopen if anything else comes up.

**Comment by mion1985** [comment]
I can't make it work as I've checked I'm getting this response:
`HTTP/1.1 401 Unauthorized..Content-Length: 0..Server: Microsoft-HTTPAPI/2.0..WWW-Authenticate: Negotiate..Date: `

**Comment by mion1985** [comment]
problem was solved. I was missing krb5.ini file in windows dir
